# Generated by Django 5.0.4 on 2024-06-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(),
        ),
    ]
